import './globals.css';

import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { NextIntlClientProvider } from 'next-intl';

import Footer from '@/app/components/Footer';
import Header from '@/app/components/Header';
import { AuthProvider } from '@/app/context/AuthProvider';
import { createClient } from '@/lib/supabase/server';

import { ErrorToastProvider } from '../components/ErrorToastProvider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Swagger editor by 404 team',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createClient();
  const { data } = await supabase.auth.getClaims();
  const isAuthenticated = !!data?.claims;

  return (
    <html className={`${geistSans.variable} ${geistMono.variable}`} lang="en">
      <body className="min-h-screen flex flex-col bg-background text-foreground antialiased">
        <NextIntlClientProvider>
          <AuthProvider initialIsAuthenticated={isAuthenticated}>
            <ErrorToastProvider>
              <Header />
              <main className="flex flex-1 flex-col">{children}</main>
              <Footer />
            </ErrorToastProvider>
          </AuthProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
